# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3749cdc60ae848712674fe2ed10fcc2d4c06c44bb39c5c8ca851ba89866536720cba1771ea0dc61727cd7ed8c0900dfa2603a1592490f8cecf518599b12e5d9

test:
  secret_key_base: a447d8642d07fe57af406e8d82c1ffcfb6e6d8308bcbac4081b8058743bc6d9515f873149b05c615fd1ad586991350e263105b713cb7d9e76fe4186be426d500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
